# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-10 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_auto_20160108_1924'),
    ]

    operations = [
        migrations.RunSQL("UPDATE elections_candidate SET email=lower(email) WHERE email!=lower(email)"),
        migrations.RunSQL("ALTER TABLE elections_candidate ADD CONSTRAINT email_must_be_lowercase CHECK (email=lower(email))"),
    ]
