# Generated by Django 3.2.14 on 2024-03-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0004_renameopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='intro',
            field=models.TextField(blank=True, verbose_name='Introduction text'),
        ),
    ]
