# Generated by Django 3.2.14 on 2023-06-13 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0018_longer_invoice_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paymentref', models.CharField(blank=True, max_length=200)),
                ('transactionobject', models.JSONField(default=dict)),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoicepaymentmethod')),
            ],
            options={
                'ordering': ('-datetime',),
                'unique_together': {('transactionid', 'paymentmethod')},
            },
        ),

        migrations.CreateModel(
            name='PlaidWebhookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('source', models.GenericIPAddressField(null=True, blank=True)),
                ('signature', models.CharField(max_length=1000)),
                ('hook_code', models.CharField(max_length=200)),
                ('contents', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
    ]
