# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-13 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0025_edit_registrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesessionvote',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
