# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-31 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import postgresqleu.util.validators


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0026_sessionvote_comment_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceseries',
            options={'ordering': ('sortkey', 'name')},
        ),
        migrations.AddField(
            model_name='conference',
            name='promoactive',
            field=models.BooleanField(default=False, verbose_name=b'Promotion active'),
        ),
        migrations.AddField(
            model_name='conference',
            name='promopicurl',
            field=models.URLField(blank=True, validators=[postgresqleu.util.validators.PictureUrlValidator(aspect=2.3)], verbose_name=b'URL to promo picture'),
        ),
        migrations.AddField(
            model_name='conference',
            name='promotext',
            field=models.TextField(blank=True, max_length=1000, verbose_name=b'Promotion text'),
        ),
        migrations.AddField(
            model_name='conferenceseries',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conferenceseries',
            name='sortkey',
            field=models.IntegerField(default=100),
        ),
    ]
