# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-21 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('newsevents', '0003_conferencenews'),
        ('confreg', '0027_confpromo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('title', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('inrss', models.BooleanField(default=True, verbose_name=b'Include in RSS feed')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsevents.NewsPosterProfile')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference')),
            ],
            options={
                'ordering': ['-datetime'],
                'verbose_name_plural': 'Conference News',
            },
        ),
    ]
