# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-09 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0030_remove_twitter_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencenews',
            name='tweeted',
            field=models.BooleanField(default=False),
        ),
    ]
