# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-09 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0031_tweet_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceTweetQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=timezone.now)),
                ('contents', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='twitter_timewindow_end',
            field=models.TimeField(default='23:59:59', verbose_name="Don't post tweets after"),
        ),
        migrations.AddField(
            model_name='conference',
            name='twitter_timewindow_start',
            field=models.TimeField(default='00:00', verbose_name="Don't post tweets before"),
        ),
        migrations.AddField(
            model_name='conferencetweetqueue',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference'),
        ),
    ]
