# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-15 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0032_tweetqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='twitterreminders_active',
            field=models.BooleanField(default=False, verbose_name='Twitter reminder DMs active'),
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Speaker reminder(s) sent'),
        ),
    ]
