# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-17 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confreg', '0034_conference_series_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceseries',
            name='administrators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
