# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-18 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0035_confseries_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencesession',
            name='htmlicon',
            field=models.CharField(blank=True, help_text=b'HTML representing an icon used for this session on the schedule (and optionally elsewhere)', max_length=100, verbose_name=b'HTML Icon'),
        ),
    ]
