# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-18 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confreg', '0037_status_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeemail',
            name='pending_regs',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name=b'Pending registrations'),
        ),
        migrations.AddField(
            model_name='attendeemail',
            name='registrations',
            field=models.ManyToManyField(blank=True, to='confreg.ConferenceRegistration', verbose_name=b'Registrations'),
        ),
        migrations.AlterField(
            model_name='attendeemail',
            name='regclasses',
            field=models.ManyToManyField(blank=True, to='confreg.RegistrationClass', verbose_name=b'Registration classes'),
        ),
    ]
