# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-27 16:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0039_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Percent to refund')),
                ('fees', models.IntegerField(help_text='This amount will be deducted from the calculated refund amount', verbose_name='Fees not to refund')),
                ('fromdate', models.DateField(help_text='Suggest for refunds starting from this date', null=True, blank=True, verbose_name='From date')),
                ('todate', models.DateField(help_text='Suggest for refunds until this date', null=True, blank=True, verbose_name='To date')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference')),
            ],
        ),
    ]
