# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models
from postgresqleu.util.fields import LowercaseEmailField


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0040_refund_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='notifyaddr',
            field=LowercaseEmailField(null=True, max_length=254, verbose_name='Notification address'),
        ),

        migrations.RunSQL("UPDATE confreg_conference SET notifyaddr=contactaddr WHERE notifyaddr IS NULL"),

        migrations.AlterField(
            model_name='conference',
            name='notifyaddr',
            field=LowercaseEmailField(null=False, max_length=254, verbose_name='Notification address'),
        ),

        migrations.AddField(
            model_name='conference',
            name='notifyregs',
            field=models.BooleanField(default=False, verbose_name='Notify about registrations'),
        ),
    ]
