# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_payment_refector'),
        ('confreg', '0041_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='paymentmethods',
            field=models.ManyToManyField(to='invoices.InvoicePaymentMethod', verbose_name='Invoice payment options'),
        ),
        migrations.RunSQL("""
INSERT INTO confreg_conference_paymentmethods (conference_id, invoicepaymentmethod_id)
SELECT c.id, m.id
FROM confreg_conference c
CROSS JOIN invoices_invoicepaymentmethod m
WHERE m.active AND m.auto"""),
    ]
