# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0043_confreg_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='public',
            field=models.BooleanField(default=False, help_text='Is the existance of this discount code public'),
        ),
    ]
