# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-27 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0044_public_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeemail',
            name='tocheckin',
            field=models.BooleanField(default=False, verbose_name='To check-in processors'),
        ),
        migrations.AddField(
            model_name='attendeemail',
            name='tovolunteers',
            field=models.BooleanField(default=False, verbose_name='To volunteers'),
        ),
    ]
