# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_europecountry'),
        ('confreg', '0045_mail_volunteer_checkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='initial_common_countries',
            field=models.ManyToManyField(blank=True, help_text='Initial set of common countries', to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='conferenceregistration',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='countries.Country', verbose_name='Country'),
        ),
    ]
