# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-01 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0046_country_optional_and_initial'),
    ]

    operations = [
        migrations.RunSQL("""WITH t(id, statustext, statusgroup) AS (VALUES
        (0, 'Submitted', NULL),
        (1, 'Approved', 'Approved+Pending'),
        (2, 'Rejected', NULL),
        (3, 'Pending', 'Approved+Pending'),
        (4, 'Reserve', 'Reserve+Pending'),
        (5, 'Pending reserve', 'Reserve+Pending'))
        INSERT INTO confreg_status_strings (id, statustext, statusgroup)
        SELECT id, statustext, statusgroup FROM t ON CONFLICT (id) DO UPDATE SET statustext=excluded.statustext, statusgroup=excluded.statusgroup""")
    ]
