# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0047_pending_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='askbadgescan',
            field=models.BooleanField(default=False, help_text='Include field for allowing sponsors to scan badge', verbose_name='Field: badge scanning'),
        ),
        migrations.AddField(
            model_name='conferenceregistration',
            name='badgescan',
            field=models.BooleanField(default=True, verbose_name='Allow sponsors get contact information (name, e-mail address, country and company name) by scanning badge'),
        ),
    ]
