# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0048_sponsor_scan_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSessionTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('slug', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='callforpaperstags',
            field=models.BooleanField(default=False, verbose_name='Use tags'),
        ),
        migrations.AddField(
            model_name='conferencesessiontag',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference'),
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='tags',
            field=models.ManyToManyField(blank=True, to='confreg.ConferenceSessionTag'),
        ),
        migrations.AlterUniqueTogether(
            name='conferencesessiontag',
            unique_together=set([('conference', 'tag'), ('conference', 'slug')]),
        ),
    ]
