# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-10 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0049_sessiontags'),
    ]

    operations = [
        # Slightly ugly, but were going to add this to auth_user even though we're in the
        # confreg application.
        migrations.RunSQL("UPDATE auth_user SET email=lower(email) WHERE email!=lower(email)"),
        migrations.RunSQL("ALTER TABLE auth_user ADD CONSTRAINT email_must_be_lowercase CHECK (email=lower(email))"),
        migrations.RunSQL("CREATE UNIQUE INDEX auth_user_email_lower_key ON auth_user USING btree(lower(email))"),

        # Then for our own tables as well
        migrations.RunSQL("UPDATE confreg_conferenceregistration SET email=lower(email) WHERE email!=lower(email)"),
        migrations.RunSQL("ALTER TABLE confreg_conferenceregistration ADD CONSTRAINT email_must_be_lowercase CHECK (email=lower(email))"),
    ]
