# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-01 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0050_lowercase_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='comment',
            field=models.CharField(blank=True, max_length=200, help_text='Internal comment for planning'),
        ),
    ]
