# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-12 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0051_roomcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availabledays',
            field=models.ManyToManyField(blank=True, to='confreg.RegistrationDay', verbose_name='Available days', help_text='Only used for schedule creation, not actual viewing!'),
        ),
    ]
