# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0052_room_availabledays'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceadditionaloption',
            name='additionaldays',
            field=models.ManyToManyField(blank=True, help_text='Adds access to additional conference day(s), even if the registration type does not', to='confreg.RegistrationDay', verbose_name='Adds access to days'),
        ),
    ]
