# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-21 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0055_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='speakerreg',
            field=models.BooleanField(default=True, help_text='Confirmed speakers on this track are allowed to register as speakers, if enabled', verbose_name='Allow speaker reg'),
        ),
    ]
