# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-23 14:37
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0057_twitter_enhancement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[#@]', 'Enter a hashtag (starting with #) or username (starting with @)')])),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference')),
            ],
            options={
                'ordering': ['hashtag'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='conferencehashtag',
            unique_together=set([('conference', 'hashtag')]),
        ),
    ]
