# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-28 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0058_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='showcompany',
            field=models.BooleanField(default=False, help_text='Show the company name on the schedule', verbose_name='Show company name'),
        ),
    ]
