# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-17 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0060_saved_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='newsjson',
        ),
    ]
