# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-28 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import postgresqleu.util.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confreg', '0061_drop_newsjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='twitter_postpolicy',
            field=models.IntegerField(choices=[(0, 'Nobody can post'), (1, "Admins can post without approval, volunteers can't post"), (2, 'Volunteers can post, require admin approval'), (3, 'Volunteers can post, require volunteer or admin approval'), (4, 'Volunteers and admins can post without approval')], default=0, verbose_name='Posting policy'),
        ),
        migrations.AddField(
            model_name='conferencetweetqueue',
            name='approvedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweetapprovals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conferencetweetqueue',
            name='imagethumb',
            field=postgresqleu.util.fields.ImageBinaryField(blank=True, max_length=100000, null=True),
        ),
    ]
