# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-29 22:53
from __future__ import unicode_literals

from django.db import migrations
import postgresqleu.util.fields


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0064_retweet_and_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='photofile',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='photo',
            field=postgresqleu.util.fields.ImageBinaryField(blank=True, null=True, verbose_name='Photo'),
        ),
        migrations.RunSQL("UPDATE confreg_speaker SET photo=decode(confreg_speaker_photo.photo, 'base64') FROM confreg_speaker_photo WHERE confreg_speaker_photo.id=confreg_speaker.id"),
        migrations.DeleteModel(
            name="Speaker_Photo",
        ),
    ]
