# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-11-05 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0065_speaker_photo_bytea'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeemail',
            name='addopts',
            field=models.ManyToManyField(blank=True, to='confreg.ConferenceAdditionalOption', verbose_name='Attendees with options'),
        ),
    ]
