# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-26 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0068_not_accepted_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpayment',
            name='createdat',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bulkpayment',
            name='paidat',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
