# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-17 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confreg', '0070_track_cancels'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRegistrationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('txt', models.CharField(max_length=8000)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.ConferenceRegistration')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='conferenceregistrationlog',
            index=models.Index(fields=['reg', '-ts'], name='confreg_con_reg_id_4afabb_idx'),
        ),
    ]
