# Generated by Django 2.2.11 on 2020-05-25 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import postgresqleu.util.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confreg', '0075_messaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossConferenceEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentat', models.DateTimeField(auto_now_add=True)),
                ('senderaddr', postgresqleu.util.fields.LowercaseEmailField(max_length=254, verbose_name='Sender address')),
                ('sendername', models.CharField(max_length=100, verbose_name='Sender name')),
                ('subject', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('sentby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrossConferenceEmailRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isexclude', models.BooleanField()),
                ('ruletype', models.CharField(max_length=10)),
                ('ruleref', models.IntegerField()),
                ('canceled', models.BooleanField()),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.CrossConferenceEmail')),
            ],
        ),
        migrations.CreateModel(
            name='CrossConferenceEmailRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', postgresqleu.util.fields.LowercaseEmailField(max_length=254)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.CrossConferenceEmail')),
            ],
            options={
                'unique_together': {('email', 'address')},
            },
        ),
    ]
