# Generated by Django 2.2.11 on 2020-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0076_track_cross_conference'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL', help_text="Link to information about the room"),
        ),
    ]
