# Generated by Django 2.2.11 on 2021-05-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0077_room_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='key_private',
            field=models.TextField(blank=True, verbose_name='Private RSA key for signatures'),
        ),
        migrations.AddField(
            model_name='conference',
            name='key_public',
            field=models.TextField(blank=True, verbose_name='Public RSA key for signatures'),
        ),
        migrations.AddField(
            model_name='conference',
            name='web_origins',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Allowed web origins for API calls (comma separated list)'),
        ),
        migrations.CreateModel(
            name='ConferenceRegistrationTemporaryToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('expires', models.DateTimeField()),
                ('reg', models.OneToOneField(on_delete=models.deletion.CASCADE, to='confreg.ConferenceRegistration')),
            ],
        ),
    ]
