# Generated by Django 3.2.11 on 2022-02-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0078_conference_api_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='jinjaenabled',
            field=models.BooleanField(default=False, verbose_name='Jinja templates enabled'),
        ),
        migrations.RunSQL(
            "UPDATE confreg_conference SET jinjaenabled=true WHERE jinjadir IS NOT NULL AND jinjadir != ''",
        ),
    ]
