# Generated by Django 3.2.11 on 2022-02-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0080_conferencesession_internalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceregistration',
            name='localoptout',
            field=models.BooleanField(default=False, verbose_name='Opt out of emails (when not connected to an account)'),
        ),
    ]
