# Generated by Django 3.2.13 on 2022-05-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0081_conferenceregistration_localoptout'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='showvotes',
            field=models.BooleanField(default=False, help_text="Show other people's votes on the talkvote page", verbose_name='Show votes'),
        ),
    ]
