# Generated by Django 3.2.11 on 2022-06-25 17:24

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0082_conference_showvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='callforpaperstimerange',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, help_text='Call for papers open between these times (if checkbox is also enabled).', null=True, verbose_name='Call for papers open between'),
        ),
        migrations.AddField(
            model_name='conference',
            name='callforsponsorstimerange',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, help_text='Call for sponsors open between these times (if checkbox is also enabled).', null=True, verbose_name='Call for sponsors open between'),
        ),
    ]
