# Generated by Django 3.2.11 on 2022-06-25 17:53

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0084_rename_active_conference_registrationopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='registrationtimerange',
            field=django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, help_text='Registration open between these times (if checkbox is also enabled).', null=True, verbose_name='Registration open between'),
        ),
    ]
