# Generated by Django 3.2.11 on 2022-06-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0085_conference_registrationtimerange'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceregistrationlog',
            name='changedata',
            field=models.CharField(blank=True, max_length=8000),
        ),
    ]
