# Generated by Django 3.2.14 on 2022-07-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0087_speaker_photo512'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='insessionlist',
            field=models.BooleanField(default=True, verbose_name='In session list'),
        ),
    ]
