# Generated by Django 3.2.14 on 2022-08-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0088_track_insessionlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='attributes',
            field=models.JSONField(default=dict, blank=True),
        ),
    ]
