# Generated by Django 3.2.14 on 2022-09-07 16:20
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0090_conferencetweetqueue_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencemessaging',
            name='socialmediamanagement',
            field=models.BooleanField(default=False, verbose_name='Social media management'),
        ),
        migrations.AddField(
            model_name='conferencetweetqueue',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name='conferencetweetqueue',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='tweetqueue_metadata_idx', opclasses=['jsonb_path_ops']),
        ),
    ]
