# Generated by Django 3.2.14 on 2022-09-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0091_conferencemessaging_socialmediamanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerassignment',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Volunteer reminder(s) sent'),
        ),
    ]
