# Generated by Django 3.2.13 on 2022-09-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0092_volunteerassignment_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
