# Generated by Django 3.2.14 on 2022-10-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0093_room_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundpattern',
            name='fees',
            field=models.DecimalField(decimal_places=2, help_text='This amount will be deducted from the calculated refund amount. Amount should be entered *without* VAT.', max_digits=10, verbose_name='Fees not to refund'),
        ),
    ]
