# Generated by Django 3.2.18 on 2023-03-03 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0095_tweet_conf_time_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='slide_upload_reminder_days',
            field=models.IntegerField(default=0, help_text='Days to wait before sending speakers reminder to upload their slides', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
