# Generated by Django 3.2.14 on 2023-06-28 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_invoice_extradescription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confreg', '0097_digisign_contracts'),
        ('util', '0004_sync_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkpayment',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='conferenceregistration',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
        migrations.AlterField(
            model_name='pendingadditionalorder',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
        migrations.AlterUniqueTogether(
            name='conferenceregistration',
            unique_together={('attendee_id', 'conference_id'), ('email', 'conference_id')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('conference', 'roomname')},
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('conference', 'trackname')},
        ),
    ]
