# Generated by Django 3.2.14 on 2023-07-24 14:12

import django.core.validators
from django.db import migrations, models
import postgresqleu.util.validators
import re


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0098_indexupdates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRemovedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlname', models.CharField(max_length=32, validators=[postgresqleu.util.validators.validate_lowercase, django.core.validators.RegexValidator(re.compile('^\\w+\\Z'), 'Enter a valid urlname consisting of letters, numbers or underscore.', 'invalid')], verbose_name='URL name')),
                ('description', models.CharField(max_length=100)),
                ('value', models.TextField()),
            ],
            options={
                'ordering': ('urlname', 'description'),
                'unique_together': {('urlname', 'description')},
            },
        ),
        migrations.RunSQL(
            "INSERT INTO confreg_conferenceremoveddata (urlname, description, value) SELECT urlname, 'additionalintro', additionalintro FROM confreg_conference WHERE additionalintro != ''",
            "UPDATE confreg_conference SET additionalintro=value FROM confreg_conferenceremoveddata WHERE confreg_conferenceremoveddata.urlname=confreg_conference.urlname AND confreg_conferenceremoveddata.description='additionalintro'",
        ),
        migrations.RunSQL(
            "INSERT INTO confreg_conferenceremoveddata (urlname, description, value) SELECT urlname, 'callforpapersintro', callforpapersintro FROM confreg_conference WHERE callforpapersintro != ''",
            "UPDATE confreg_conference SET callforpapersintro=value FROM confreg_conferenceremoveddata WHERE confreg_conferenceremoveddata.urlname=confreg_conference.urlname AND confreg_conferenceremoveddata.description='callforpapersintro'",
        ),
        migrations.RunSQL(
            "INSERT INTO confreg_conferenceremoveddata (urlname, description, value) SELECT urlname, 'welcomemail', welcomemail FROM confreg_conference WHERE welcomemail != ''",
            "UPDATE confreg_conference SET welcomemail=value FROM confreg_conferenceremoveddata WHERE confreg_conferenceremoveddata.urlname=confreg_conference.urlname AND confreg_conferenceremoveddata.description='welcomemail'",
        ),
        migrations.RemoveField(
            model_name="Conference",
            name="additionalintro",
        ),
        migrations.RemoveField(
            model_name="Conference",
            name="callforpapersintro",
        ),
        migrations.RemoveField(
            model_name="Conference",
            name="welcomemail",
        ),
    ]
