# Generated by Django 3.2.14 on 2023-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0099_remove_intro_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='confirmpolicy',
            field=models.BooleanField(default=False, help_text='Require each attendee to confirm a conference policy (as a separate step in the registration) before tickets are issued', verbose_name='Require policy confirmation'),
        ),
        migrations.AddField(
            model_name='conferenceregistration',
            name='policyconfirmedat',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Policy confirmed at'),
        ),
    ]
