# Generated by Django 3.2.14 on 2023-07-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0100_conference_confirmpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='dynafields',
            field=models.CharField(blank=True, help_text='Dynamic properties that can be assigned to registrations', max_length=500, verbose_name='Dynamic properties'),
        ),
        migrations.AddField(
            model_name='conferenceregistration',
            name='dynaprops',
            field=models.JSONField(default=dict, blank=True),
        ),
    ]
