# Generated by Django 3.2.14 on 2023-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0101_dynprops'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceadditionaloption',
            options={'ordering': ['conference', 'sortkey', 'name']},
        ),
        migrations.AddField(
            model_name='conferenceadditionaloption',
            name='sortkey',
            field=models.IntegerField(default=100, verbose_name="Sort key"),
        ),
    ]
