# Generated by Django 3.2.14 on 2023-10-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0102_additionaloptions_sortkey'),
    ]

    operations = [
        migrations.RunSQL(
            # We can safely overwrite the whole 'social' value since nothing existed there before this.
            "UPDATE confreg_speaker SET attributes = attributes || jsonb_build_object('social', jsonb_build_object('twitter', twittername)) WHERE twittername != ''",
            "UPDATE confreg_speaker SET twittername=attributes->'social'->>'twitter' WHERE attributes->'social'->>'twitter' != ''",
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='twittername',
        ),
        # We can't set USING in an AlterField, so we first have to alter it ourselves, and then
        # alter again using the django method.
        # In the reverse django will have already converted it to a text field with embedded json
        # string, so we have to turn it back into json and then extract it
        migrations.RunSQL(
            "ALTER TABLE confreg_conferencetweetqueue ALTER COLUMN contents TYPE jsonb USING to_jsonb(contents)",
            "UPDATE confreg_conferencetweetqueue SET contents=json_build_array(contents::jsonb)->>0",
        ),
        migrations.AlterField(
            model_name='conferencetweetqueue',
            name='contents',
            field=models.JSONField(null=False, blank=False),
        ),
    ]
