# Generated by Django 3.2.14 on 2023-10-16 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0103_speaker_twittername_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencetweetqueue',
            name='errorcount',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ConferenceTweetQueueErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=250)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.conferencetweetqueue')),
            ],
            options={
                'ordering': ('ts', ),
            },
        ),
    ]
