# Generated by Django 3.2.14 on 2023-10-17 14:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0104_social_media_error_handling'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceregistration',
            name='favs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], size=None),
            preserve_default=False,
        ),
    ]
