# Generated by Django 3.2.14 on 2023-11-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0106_invoicetransfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='scannerfields',
            field=models.CharField(blank=True, help_text='Dynamic properties usd in the badge scanner interface', max_length=500, verbose_name='Scanning properties'),
        ),
    ]
