# Generated by Django 3.2.14 on 2024-01-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0108_alter_conferencesessionfeedback_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='videoproviders',
            field=models.CharField(blank=True, max_length=200, verbose_name='Video link providers'),
        ),
        migrations.AddField(
            model_name='conferencesession',
            name='videolinks',
            field=models.JSONField(default=dict, verbose_name='Video links'),
        ),
    ]
