# Generated by Django 3.2.14 on 2024-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0109_videolinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='tbdinschedule',
            field=models.BooleanField(default=False, help_text='Include pending sessions as TBD on schedule', verbose_name='TBD sessions in schedule'),
        ),
    ]
