# Generated by Django 3.2.14 on 2024-01-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0110_conference_tbdinschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferencehashtag',
            options={'ordering': ['sortkey', 'hashtag']},
        ),
        migrations.AddField(
            model_name='conferencehashtag',
            name='autoadd',
            field=models.BooleanField(default=False, help_text='Automatically add hashtag to news posts and as initial content of manual posts', verbose_name='Auto add'),
        ),
        migrations.AddField(
            model_name='conferencehashtag',
            name='sortkey',
            field=models.IntegerField(default=100),
        ),
    ]
