# Generated by Django 4.2.11 on 2024-05-14 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0112_unique_regtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeemail',
            name='sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='attendeemail',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='attendeemail',
            index=models.Index(condition=models.Q(('sent', False)), fields=['sentat'], name='confreg_attendeemail_unsent'),
        ),
    ]
