# Generated by Django 4.2.11 on 2024-05-18 09:18

from django.db import migrations, models
from django.core.validators import MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0113_attendeemail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='callforpapersmaxsubmissions',
            field=models.IntegerField(default=0, help_text='Maximum number of submissions per speaker, 0 for unlimited', verbose_name='Max submissions', validators=[MinValueValidator(0)], ),
        ),
    ]
