# Generated by Django 4.2.11 on 2024-08-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0114_conference_callforpapersmaxsubmissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='photo512_hashval',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='photo_hashval',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.RunSQL(
            """
CREATE FUNCTION confreg_speaker_update_hash() RETURNS trigger AS $$
BEGIN
        NEW.photo_hashval = decode(md5(NEW.photo), 'hex');
        NEW.photo512_hashval = decode(md5(NEW.photo512), 'hex');
        RETURN NEW;
END;
$$ LANGUAGE plpgsql
        """,
            "DROP FUNCTION confreg_speaker_update_hash();",
        ),
        migrations.RunSQL(
            """
CREATE TRIGGER confreg_speaker_update_hash_trigger
BEFORE INSERT OR UPDATE OF photo, photo512 ON confreg_speaker
FOR EACH ROW EXECUTE FUNCTION confreg_speaker_update_hash();
            """,
            "DROP TRIGGER confreg_speaker_update_hash_trigger",
        ),
        migrations.RunSQL(
            "UPDATE confreg_speaker SET photo_hashval=decode(md5(photo), 'hex'), photo512_hashval=decode(md5(photo512), 'hex') WHERE photo IS NOT NULL OR photo512 IS NOT NULL",
            "",
        ),
    ]
