# Generated by Django 4.2.16 on 2024-09-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0115_speaker_photo_hashvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='scoring_method',
            field=models.IntegerField(choices=[(0, 'Average'), (1, 'Olympic Average')], default=0, verbose_name='Scoring method'),
        ),
    ]
