# Generated by Django 4.2.11 on 2025-01-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0116_conference_scoring_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='askpronouns',
            field=models.BooleanField(default=False, help_text='Include fields for pronouns', verbose_name='Field: pronouns'),
        ),
        migrations.AddField(
            model_name='conferenceregistration',
            name='pronouns',
            field=models.IntegerField(choices=[(0, ''), (1, 'she/her'), (2, 'he/him'), (3, 'they/them'), (4, 'other')], default=0),
        ),
        migrations.CreateModel(
            name='AggregatePronouns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pronouns', models.IntegerField(choices=[(0, ''), (1, 'she/her'), (2, 'he/him'), (3, 'they/them'), (4, 'other')], default=0)),
                ('num', models.IntegerField()),
                ('conference', models.ForeignKey(on_delete=models.deletion.CASCADE, to='confreg.conference')),
            ],
            options={
                'unique_together': {('conference', 'pronouns')},
            },
        ),
    ]
