# Generated by Django 3.2.22 on 2025-07-19 19:52

from django.db import migrations, models
import postgresqleu.util.forms


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0117_pronouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='permissions',
            field=postgresqleu.util.forms.ChoiceArrayField(base_field=models.CharField(choices=[('regtypes', 'Registration types and counters'), ('discounts', 'Discount codes'), ('discountspublic', 'Public discount codes'), ('vouchers', 'Voucher codes'), ('sponsors', 'Sponsors and counts'), ('addopts', 'Additional options and counts'), ('schedule', 'Schedule JSON'), ('sponsorlevels', 'Sponsor level metadata'), ('sponsorclaims', 'Sponsor claimed benefits'), ('sessions', 'Sessions')], max_length=32), size=None),
        ),
    ]
