# Generated by Django 4.2.11 on 2025-08-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0117_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationtype',
            name='checkinmessage',
            field=models.TextField(blank=True, help_text='Message shown when the attendee is checked in', verbose_name='Check-in message'),
        ),
    ]
