# Generated by Django 4.2.11 on 2025-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0118_registrationtype_checkinmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceadditionaloption',
            name='requires_attendee',
            field=models.ManyToManyField(blank=True, help_text='Can only be picked by specific attendees', to='confreg.conferenceregistration', verbose_name='Requires specific attendee'),
        ),
    ]
