# Generated by Django 4.2.11 on 2025-09-22 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0119_conferenceadditionaloption_requires_attendee'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE TABLE IF NOT EXISTS pronouns_text(id int not null primary key, pronountext text not null)",
            "DROP TABLE pronouns_text",
        ),
        migrations.RunSQL(
            """WITH t(id, pronountext) AS (VALUES
               (0, ''),
               (1, 'she/her'),
               (2, 'he/him'),
               (3, 'they/them'),
               (4, 'other')
            ) MERGE INTO pronouns_text p USING t ON t.id=p.id WHEN MATCHED AND t.pronountext != p.pronountext THEN UPDATE SET pronountext=t.pronountext WHEN NOT MATCHED THEN INSERT (id, pronountext) VALUES (t.id, t.pronountext)""",
            "DELETE FROM pronouns_text",
        )
    ]
