# Generated by Django 4.2.11 on 2025-10-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0120_pronounstext'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceregistration',
            name='checkinmessage',
            field=models.CharField(blank=True, help_text='Message shown when the attendee is checked in', max_length=500, verbose_name='Check-in message'),
        ),
    ]
