# Generated by Django 4.2.11 on 2025-12-03 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('confreg', '0121_conferenceregistration_checkinmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conferenceregistration',
            unique_together={('attendee', 'conference')},
        ),
        migrations.AddConstraint(
            model_name='conferenceregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('canceledat__isnull', True)), fields=('conference', 'email'), name='reg_unique_email_for_not_canceled'),
        ),
    ]
