# Generated by Django 4.2.11 on 2025-12-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0122_dupe_email_for_canceled'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceregistration',
            name='cancelreason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='conferenceregistration',
            name='cancelrequestedat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conference',
            name='allowcancel',
            field=models.BooleanField(blank=False, null=False, default=True, verbose_name="Allow canceling registrations"),
        ),
    ]
