# Generated by Django 4.2.11 on 2026-01-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0123_cancelrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeemail',
            name='extracontext',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
