# Generated by Django 4.2.11 on 2026-02-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0124_attendeemail_extracontext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='enddate',
            field=models.DateField(db_index=True, verbose_name='End date'),
        ),
    ]
