# Generated by Django 4.2.11 on 2026-03-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0125_index_conference_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='askcity',
            field=models.BooleanField(default=False, help_text='Include field for city', verbose_name='Field: city'),
        ),
        migrations.AddField(
            model_name='conference',
            name='askcountry',
            field=models.BooleanField(default=True, help_text='Include field for country', verbose_name='Field: country'),
        ),
        migrations.AddField(
            model_name='conferenceregistration',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='City'),
            preserve_default=False,
        ),
    ]
