# Generated by Django 3.2.14 on 2023-05-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigisignProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('displayname', models.CharField(max_length=100)),
                ('classname', models.CharField(max_length=200, verbose_name='Implementation class')),
                ('active', models.BooleanField(default=False)),
                ('config', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DigisignDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentid', models.CharField(blank=True, max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digisign.digisignprovider')),
                ('handler', models.CharField(blank=True, max_length=32)),
                ('completed', models.BooleanField(null=False, blank=False, default=False)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='digisigndocument',
            unique_together=set([('documentid', 'provider')]),
        ),
        migrations.CreateModel(
            name='DigisignLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=1000)),
                ('fulldata', models.JSONField(default=dict)),
                ('document', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='digisign.digisigndocument')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digisign.digisignprovider')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.AddIndex(
            model_name='digisignlog',
            index=models.Index(fields=['document', '-time'], name='digisign_di_documen_79688b_idx'),
        ),
    ]
