# Generated by Django 3.2.14 on 2023-10-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digisign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='digisigndocument',
            name='firstsigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunSQL(
            "ALTER TABLE digisign_digisigndocument ADD COLUMN completed_d timestamptz NULL",
            "",
        ),
        migrations.RunSQL(
            # XXX: only for signwell, but that's all we supported at this point in time
            "UPDATE digisign_digisigndocument SET completed_d=(SELECT max(time) FROM digisign_digisignlog l WHERE l.document_id=digisign_digisigndocument.id AND l.event='document_completed') WHERE completed",
            "",
        ),
        migrations.RunSQL(
            "ALTER TABLE digisign_digisigndocument DROP COLUMN completed",
            "",
        ),
        migrations.RunSQL(
            "ALTER TABLE digisign_digisigndocument RENAME COLUMN completed_d TO completed",
            "",
        ),
        migrations.AlterField(
            model_name='digisigndocument',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
