# Generated by Django 4.2.11 on 2024-06-21 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0020_regtransfer_processor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GocardlessTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('paymentref', models.CharField(blank=True, max_length=200)),
                ('transactionobject', models.JSONField(default=dict)),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoicepaymentmethod')),
            ],
            options={
                'ordering': ('-date', 'transactionid'),
                'unique_together': {('transactionid', 'paymentmethod')},
            },
        ),
    ]
