from django.urls import re_path

from . import views
from . import backendviews
from . import scanning

# All urls already start with /events/sponsor/
urlpatterns = [
    re_path(r'^$', views.sponsor_dashboard),
    re_path(r'^(\d+)/$', views.sponsor_conference),
    re_path(r'^(\d+)/claim/(\d+)/$', views.sponsor_claim_benefit),
    re_path(r'^(\d+)/managers/add/$', views.sponsor_manager_add),
    re_path(r'^(\d+)/managers/del/$', views.sponsor_manager_delete),
    re_path(r'^(\d+)/viewmail/(\d+)/$', views.sponsor_view_mail),
    re_path(r'^(\d+)/purchase/voucher/$', views.sponsor_purchase_voucher),
    re_path(r'^(\d+)/purchase/discountcode/$', views.sponsor_purchase_discount),
    re_path(r'^(\d+)/shipments/new/$', views.sponsor_shipment_new),
    re_path(r'^(\d+)/shipments/(\d+)/$', views.sponsor_shipment),
    re_path(r'^(\d+)/scanning/$', scanning.sponsor_scanning),
    re_path(r'^(\d+)/scanning/download.csv/$', scanning.sponsor_scanning_download),
    re_path(r'^(\d+)/contractview/$', views.sponsor_contractview),
    re_path(r'^scanning/([a-z0-9]{64})/$', scanning.scanning_page),
    re_path(r'^scanning/([a-z0-9]{64})/api/(\w+)/$', scanning.scanning_api),
    re_path(r'^scanning-test/$', scanning.testcode),
    re_path(r'^signup/(\w+)/$', views.sponsor_signup_dashboard),
    re_path(r'^signup/(\w+)/(\w+)/$', views.sponsor_signup),
    re_path(r'^previewcontract/(\d+)/$', views.sponsor_contract_preview),
    re_path(r'^shipments/([a-z0-9]+)/$', views.sponsor_shipment_receiver),
    re_path(r'^shipments/([a-z0-9]+)/(\d+)/$', views.sponsor_shipment_receiver_shipment),
    re_path(r'^admin/imageview/(\d+)/$', views.sponsor_admin_imageview),
    re_path(r'^admin/downloadfile/(\d+)/$', views.sponsor_admin_downloadfile),
    re_path(r'^admin/(\w+)/$', views.sponsor_admin_dashboard),
    re_path(r'^admin/(\w+)/(\d+)/$', views.sponsor_admin_sponsor),
    re_path(r'^admin/(\w+)/(\d+)/edit/$', backendviews.edit_sponsor),
    re_path(r'^admin/(\w+)/(\d+)/contractlog/$', views.sponsor_admin_sponsor_contractlog),
    re_path(r'^admin/(\w+)/(\d+)/contractview/$', views.sponsor_admin_sponsor_contractview),
    re_path(r'^admin/(\w+)/(\d+)/resendcontract/$', views.sponsor_admin_sponsor_resendcontract),
    re_path(r'^admin/(\w+)/(\d+)/addcontract/$', views.sponsor_admin_addcontract),
    re_path(r'^admin/(\w+)/(\d+)/markaddcontract/$', views.sponsor_admin_markaddcontract),
    re_path(r'^admin/(\w+)/(\d+)/viewaddcontract/(\d+)/$', views.sponsor_admin_viewaddcontract),
    re_path(r'^admin/(\w+)/benefit/(\d+)/$', views.sponsor_admin_benefit),
    re_path(r'^admin/(\w+)/sendmail/$', views.sponsor_admin_send_mail),
    re_path(r'^admin/(\w+)/viewmail/(\d+)/$', views.sponsor_admin_view_mail),
    re_path(r'^admin/(\w+)/testvat/$', views.sponsor_admin_test_vat),
    re_path(r'^admin/(\w+)/benefitreports/$', views.sponsor_admin_benefit_reports),
    re_path(r'^admin/(\w+)/levels/(.*/)?$', backendviews.edit_sponsorship_levels),
    re_path(r'^admin/(\w+)/contracts/(\d+)/editfields/$', backendviews.edit_sponsorship_contract_fields),
    re_path(r'^admin/(\w+)/contracts/(\d+)/previewfields/$', backendviews.preview_sponsorship_contract_fields),
    re_path(r'^admin/(\w+)/contracts/(\d+)/editdigifields/$', backendviews.edit_sponsorship_digital_contract_fields),
    re_path(r'^admin/(\w+)/contracts/(\d+)/sendtest/$', backendviews.send_test_sponsorship_contract),
    re_path(r'^admin/(\w+)/contracts/(\d+)/copyfields/$', backendviews.copy_sponsorship_contract_fields),
    re_path(r'^admin/(\w+)/contracts/(.*/)?$', backendviews.edit_sponsorship_contracts),
    re_path(r'^admin/(\w+)/addresses/(.*/)?$', backendviews.edit_shipment_addresses),
    re_path(r'^admin/(\w+)/shipments/new/$', views.admin_shipment_new),
    re_path(r'^admin/(\w+)/shipments/(\d+)/$', views.admin_shipment),
    re_path(r'^admin/(\w+)/(\d+)/refund/$', views.sponsor_admin_refund),
    re_path(r'^admin/(\w+)/(\d+)/reissue/$', views.sponsor_admin_reissue),
    re_path(r'^admin/(\w+)/badgescanstatus/$', scanning.admin_scan_status),
]
