# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-31 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_return_banktransaction'),
        ('transferwise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferwisePayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reference', models.CharField(max_length=100)),
                ('uuid', models.UUIDField(unique=True)),
                ('transferid', models.BigIntegerField(null=True)),
                ('accid', models.BigIntegerField(null=True)),
                ('quoteid', models.BigIntegerField(null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('sentat', models.DateTimeField(blank=True, null=True)),
                ('completedat', models.DateTimeField(blank=True, null=True)),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod')),
            ],
        ),
    ]
