# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-06-28 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transferwise', '0003_transferwisepayout_counterpart'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferwisepayout',
            name='completedtrans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transferwise.TransferwiseTransaction'),
        ),
        migrations.AlterField(
            model_name='transferwisepayout',
            name='reference',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
