# Generated by Django 4.2.11 on 2025-06-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transferwise', '0005_transferwise_monthly_statements'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransferwiseMonthlyStatement',
        ),
    ]
