# Generated by Django 4.2.11 on 2024-10-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_europecountry'),
    ]

    operations = [
        migrations.RunSQL("UPDATE country SET name='NORTH MACEDONIA', printable_name='North Macedonia' WHERE iso='MK'"),
    ]
