# Generated by Django 5.2.10 on 2026-09-21 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0021_alter_vatrate_vatpercent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QontoTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qontoid', models.UUIDField(unique=True)),
                ('datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('operation_type', models.CharField(max_length=32)),
                ('paymentref', models.CharField(blank=True, max_length=200)),
                ('counterpart_iban', models.CharField(blank=True, max_length=100)),
                ('counterpart_bic', models.CharField(blank=True, max_length=100)),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoicepaymentmethod')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
    ]
