# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
        ('confsponsor', '0018_contract_storage_inline')
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE util_storage ALTER COLUMN data TYPE bytea USING decode(data, 'base64')"),
        migrations.AlterField(
            model_name='storage',
            name='data',
            field=models.BinaryField(),
        ),
        migrations.AlterUniqueTogether(
            name='storage',
            unique_together=set([('key', 'storageid')]),
        ),
    ]
