# Generated by Django 2.2.11 on 2020-04-20 20:26

from django.db import migrations, models
from django.conf import settings


def migrate_twitter(apps, schema_editor):
    if getattr(settings, 'TWITTER_CLIENT', None):
        apps.get_model('util', 'OAuthApplication')(name='twitter', baseurl='https://api.twitter.com', client=settings.TWITTER_CLIENT, secret=settings.TWITTER_CLIENTSECRET).save()


def unmigrate_twitter(apps, schema_editor):
    apps.get_model('util', 'OAuthApplication').objects.filter(name='twitter').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0002_bytea_smarter_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=False, blank=False)),
                ('baseurl', models.URLField(max_length=100, null=False, blank=False, unique=True, verbose_name='Base URL')),
                ('client', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'OAuth Application',
            },
        ),
        migrations.RunPython(migrate_twitter, unmigrate_twitter),
    ]
