# Generated by Django 3.2.14 on 2024-04-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0004_sync_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='hashval',
            field=models.BinaryField(blank=True, null=True),
        ),

        migrations.RunSQL(
            """
CREATE FUNCTION util_storage_update_hash() RETURNS trigger AS $$
BEGIN
        NEW.hashval = decode(md5(NEW.data), 'hex');
        RETURN NEW;
END;
$$ LANGUAGE plpgsql
        """,
            "DROP FUNCTION util_storage_update_hash();",
        ),

        migrations.RunSQL(
            """
CREATE TRIGGER utiL_storage_update_hash_trigger
BEFORE UPDATE OF data ON util_storage
FOR EACH ROW EXECUTE FUNCTION util_storage_update_hash();
            """,
            "DROP TRIGGER util_storage_update_hash_trigger",
        ),

        migrations.RunSQL(
            "UPDATE util_storage SET hashval=decode(md5(data), 'hex')",
            "",
        ),

        migrations.AlterField(
            model_name='storage',
            name='hashval',
            field=models.BinaryField(blank=False, null=False),
        ),
    ]
