# Generated by Django 3.2.14 on 2024-04-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0005_storage_hashval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='hashval',
            field=models.BinaryField(null=True),
        ),
    ]
