# Generated by Django 3.2.14 on 2024-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0006_alter_storage_hashval'),
    ]

    operations = [
        migrations.RunSQL(
            """
CREATE OR REPLACE TRIGGER utiL_storage_update_hash_trigger
BEFORE INSERT OR UPDATE OF data ON util_storage
FOR EACH ROW EXECUTE FUNCTION util_storage_update_hash()
            """,
            "",
        ),

        migrations.RunSQL(
            "UPDATE util_storage SET hashval=decode(md5(data), 'hex') WHERE hashval IS NULL",
            "",
        ),

        migrations.AlterField(
            model_name='storage',
            name='hashval',
            field=models.BinaryField(blank=False, null=False),
        ),

    ]
