# Generated by Django 4.2.11 on 2025-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0007_storage_trigger_fix'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
