# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-28 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjob',
            name='command',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
