# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-22 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confwiki', '0002_signup_optionvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='notify_changes',
            field=models.BooleanField(default=False, help_text='Send email notifications when attendees sign up or change their signup information'),
        ),
    ]
