# Generated by Django 4.2.11 on 2024-05-14 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailqueue', '0002_subject_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedmail',
            name='regtime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
