# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_payment_refector'),
        ('adyen', '0002_adyen_decimal_amount'),
    ]

    operations = [
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE"),
        migrations.AddField(
            model_name='adyenlog',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AddField(
            model_name='rawnotification',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AddField(
            model_name='report',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AddField(
            model_name='transactionstatus',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.RunSQL(
            "UPDATE adyen_adyenlog SET paymentmethod_id = (SELECT id FROM invoices_invoicepaymentmethod WHERE classname='postgresqleu.util.payment.adyen.AdyenCreditcard') WHERE paymentmethod_id IS NULL",
        ),
        migrations.RunSQL(
            "UPDATE adyen_rawnotification SET paymentmethod_id = (SELECT id FROM invoices_invoicepaymentmethod WHERE classname='postgresqleu.util.payment.adyen.AdyenCreditcard') WHERE paymentmethod_id IS NULL",
        ),
        migrations.RunSQL(
            "UPDATE adyen_report SET paymentmethod_id = (SELECT id FROM invoices_invoicepaymentmethod WHERE classname='postgresqleu.util.payment.adyen.AdyenCreditcard') WHERE paymentmethod_id IS NULL",
        ),
        migrations.RunSQL(
            "UPDATE adyen_transactionstatus SET paymentmethod_id = (SELECT id FROM invoices_invoicepaymentmethod WHERE classname='postgresqleu.util.payment.adyen.AdyenCreditcard') WHERE paymentmethod_id IS NULL AND (method != 'bankTransfer_IBAN' OR method IS NULL)",
        ),
        migrations.RunSQL(
            "UPDATE adyen_transactionstatus SET paymentmethod_id = (SELECT id FROM invoices_invoicepaymentmethod WHERE classname='postgresqleu.util.payment.adyen.AdyenBanktransfer') WHERE paymentmethod_id IS NULL AND method = 'bankTransfer_IBAN'",
        ),
        migrations.AlterField(
            model_name='adyenlog',
            name='paymentmethod',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AlterField(
            model_name='rawnotification',
            name='paymentmethod',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AlterField(
            model_name='report',
            name='paymentmethod',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AlterField(
            model_name='transactionstatus',
            name='paymentmethod',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
    ]
