# Generated by Django 3.2.14 on 2022-10-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adyen', '0003_payment_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adyen.transactionstatus'),
        ),
    ]
