# Generated by Django 5.2.10 on 2026-09-21 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adyen', '0004_alter_refund_transaction'),
        ('invoices', '0021_alter_vatrate_vatpercent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdyenInvoicePaymentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField()),
                ('linkid', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('forceexpire', models.BooleanField(default=False)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='invoices.invoice')),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoicepaymentmethod')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('invoice', 'paymentmethod'), name='unique_invoice_paymentmethod')],
            },
        ),
    ]
