# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0007_contract_per_conference'),
    ]

    operations = [
        migrations.RunSQL("UPDATE confsponsor_sponsorshipbenefit SET class_parameters='{}' WHERE class_parameters=''"),
        migrations.AlterField(
            model_name='sponsorshipbenefit',
            name='class_parameters',
            field=models.JSONField(blank=True),
        ),
    ]
