# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 20:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0007_contract_per_conference'),
    ]

    operations = [
        migrations.RunSQL("UPDATE confsponsor_sponsorshipbenefit SET class_parameters='{}' WHERE class_parameters=''"),
        migrations.AlterField(
            model_name='sponsorshipbenefit',
            name='class_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
