# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0008_class_params_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='vatnumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='vatstatus',
            field=models.IntegerField(choices=[(0, b'Company is from inside EU and has VAT number'), (1, b'Company is from inside EU, but does not have VAT number'), (2, b'Company is from outside EU')], null=True),
        ),
    ]
