# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-09 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0009_vat_allow_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipbenefit',
            name='tweet_template',
            field=models.TextField(blank=True),
        ),
    ]
