# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-06 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0010_benefit_tweet_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiplevel',
            name='maxnumber',
            field=models.IntegerField(default=0, verbose_name='Maximum number of sponsors'),
        ),
    ]
