# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-16 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import postgresqleu.util.random


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0043_confreg_indexes'),
        ('confsponsor', '0012_sponsor_cc_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresstoken', models.BigIntegerField()),
                ('description', models.CharField(max_length=200)),
                ('sent_parcels', models.IntegerField(help_text='Number of parcels sent', verbose_name='Parcel count')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Shipment sent at')),
                ('arrived_at', models.DateTimeField(blank=True, help_text='Parcels arrived at', null=True)),
                ('arrived_parcels', models.IntegerField(help_text='Number of parcels arrived')),
                ('trackingnumber', models.CharField(blank=True, max_length=100, verbose_name='Tracking number')),
                ('shippingcompany', models.CharField(blank=True, max_length=100, verbose_name='Shipping company')),
                ('trackinglink', models.URLField(blank=True, verbose_name='Tracking link')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Can address be viewed?')),
                ('startdate', models.DateField(blank=True, help_text='Shipments cannot arrive before', null=True)),
                ('enddate', models.DateField(blank=True, help_text='Shipments cannot arrive after', null=True)),
                ('token', models.TextField(default=postgresqleu.util.random.generate_random_token, help_text='Token used by arriving party to indicate shipments', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('available_to', models.ManyToManyField(help_text='Which sponsorsihp levels is this address available to', to='confsponsor.SponsorshipLevel')),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference')),
            ],
            options={
                'ordering': ('startdate', 'enddate', 'title'),
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confsponsor.ShipmentAddress'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confsponsor.Sponsor'),
        ),
        migrations.AlterUniqueTogether(
            name='shipment',
            unique_together=set([('conference', 'addresstoken')]),
        ),
    ]
