# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-01 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0013_shipments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsormail',
            name='sponsors',
            field=models.ManyToManyField(blank=True, to='confsponsor.Sponsor'),
        ),
    ]
