# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-02 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confreg', '0048_sponsor_scan_attendees'),
        ('confsponsor', '0014_sponsor_individual_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedAttendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scannedat', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_by', to='confreg.ConferenceRegistration')),
                ('scannedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_attendees', to='confreg.ConferenceRegistration')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confsponsor.Sponsor')),
            ],
            options={
                'ordering': ('-scannedat',),
            },
        ),
        migrations.CreateModel(
            name='SponsorScanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.ConferenceRegistration')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confsponsor.Sponsor')),
            ],
        ),
        migrations.AlterField(
            model_name='sponsorshipbenefit',
            name='benefit_class',
            field=models.IntegerField(blank=True, choices=[(0, 'Automatically claimed'), (1, 'Require uploaded image'), (2, 'Requires explicit claiming'), (3, 'Claim entry vouchers'), (4, 'Provide text string'), (5, 'List of attendee email addresses'), (6, 'Scanning of attendee badges'), (7, 'Submit session'), (8, 'Upload file')], default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sponsorscanner',
            unique_together=set([('sponsor', 'scanner')]),
        ),
        migrations.AlterUniqueTogether(
            name='scannedattendee',
            unique_together=set([('sponsor', 'scannedby', 'attendee')]),
        ),
    ]
