# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-23 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0015_sponsor_scan_attendees'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedvoucher',
            name='conference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference'),
        ),
        migrations.RunSQL(
            "UPDATE confsponsor_purchasedvoucher SET conference_id = s.conference_id FROM confsponsor_sponsor s WHERE s.id=sponsor_id",
        ),
        migrations.AlterField(
            model_name='purchasedvoucher',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confreg.Conference'),
        ),
        migrations.AlterField(
            model_name='purchasedvoucher',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confsponsor.Sponsor'),
        ),
    ]
