# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-28 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0016_prepaid_batches_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiplevel',
            name='public',
            field=models.BooleanField(default=True, help_text='If unchecked the sponsorship level will be treated as internal, for example for testing', verbose_name='Publicly visible'),
        ),
    ]
