# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-10-29 15:51
from __future__ import unicode_literals

from django.db import migrations
import postgresqleu.util.fields


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0017_nonpublic_sponsorshiplevel'),
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorshipcontract',
            name='contractpdf',
            field=postgresqleu.util.fields.PdfBinaryField(max_length=1000000),
        ),
        migrations.RunSQL("UPDATE confsponsor_sponsorshipcontract SET contractpdf=decode(util_storage.data, 'base64') FROM util_storage WHERE key='sponsorcontract' AND storageid=confsponsor_sponsorshipcontract.id"),
        migrations.RunSQL("DELETE FROM util_storage WHERE key='sponsorcontract'"),
    ]
