# Generated by Django 3.2.14 on 2022-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0019_purchasedvoucher_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorclaimedbenefit',
            name='claimjson',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "UPDATE confsponsor_sponsorclaimedbenefit SET claimjson=CASE WHEN b.benefit_class=3 THEN jsonb_build_object('batchid', claimdata::int) WHEN b.benefit_class=4 THEN jsonb_build_object('text', claimdata) END FROM confsponsor_sponsorshipbenefit b WHERE b.id=benefit_id AND b.benefit_class IN (3,4)",
            "UPDATE confsponsor_sponsorclaimedbenefit SET claimdata=COALESCE(claimjson ->> 'batchid', claimjson ->> 'text') WHERE claimjson != '{}'",
        ),
        migrations.RemoveField(
            model_name='sponsorclaimedbenefit',
            name='claimdata',
        ),
    ]
