# Generated by Django 3.2.14 on 2023-01-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0020_claimjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedattendee',
            name='firstscan',
            field=models.BooleanField(default=True),
        ),
    ]
