# Generated by Django 3.2.14 on 2023-06-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0022_sponsorship_digital_contracts'),
        ('util', '0004_sync_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiplevel',
            name='invoiceextradescription',
            field=models.TextField(blank=True, help_text='Extra description to be added to invoices, included in payment information and in the email sent.', verbose_name='Invoice extra description'),
        ),
    ]
