# Generated by Django 3.2.14 on 2023-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0024_indexupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipbenefit',
            name='autoconfirm',
            field=models.BooleanField(default=False, help_text="Automatically confirm this benefit when it's claimed", verbose_name='Automatically confirm'),
        ),
        migrations.RunSQL(
            "UPDATE confsponsor_sponsorshipbenefit SET autoconfirm=true, class_parameters = class_parameters - 'autoconfirm' WHERE (class_parameters->'autoconfirm')::boolean",
            "UPDATE confsponsor_sponsorshipbenefit SET class_parameters = class_parameters || jsonb_build_object('autoconfirm', true) WHERE autoconfirm",
        ),
        migrations.RunSQL(
            # Prior to this patch all entry vouchers were always autoconfirmed, so set all existing
            # entries to that.
            "UPDATE confsponsor_sponsorshipbenefit SET autoconfirm=true WHERE benefit_class=3",
        ),
    ]
