# Generated by Django 3.2.14 on 2023-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0025_sponsorshipbenefit_autoconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='social',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunSQL(
            "UPDATE confsponsor_sponsor SET social=jsonb_build_object('twitter', twittername) WHERE twittername != ''",
            "UPDATE confsponsor_sponsor SET twittername=social->>'twitter' WHERE social->>'twitter' != ''",
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='twittername',
        ),
    ]
