# Generated by Django 4.2.11 on 2024-06-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0031_sponsormail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshipbenefit',
            name='include_in_data',
            field=models.BooleanField(default=True, help_text='Include information about this benefit in sponsorship data from tokens', verbose_name='Include in data'),
        ),
    ]
