# Generated by Django 3.2.22 on 2024-11-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0032_sponsorshipbenefit_include_in_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiplevel',
            name='paymentdeadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='payment deadline'),
        ),
        migrations.AddField(
            model_name='sponsorshiplevel',
            name='paymentterms',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Number of days until payment is due'),
        ),
    ]
