# Generated by Django 4.2.11 on 2025-02-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0033_payment_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshiplevel',
            name='contractlevel',
            field=models.IntegerField(choices=[(0, 'No contract'), (1, 'Click-through contract'), (2, 'Full contract')], default=0, verbose_name='Contract level'),
        ),
        migrations.RunSQL("""
UPDATE confsponsor_sponsorshiplevel SET contractlevel=CASE
WHEN instantbuy AND contract_id IS NOT NULL THEN 1
WHEN instantbuy AND contract_id IS NULL THEN 0
ELSE 2 END""",
                          """
UPDATE confsponsor_sponsorshiplevel SET instantbuy=(contractlevel < 2)"""),
        migrations.RemoveField(
            model_name='sponsorshiplevel',
            name='instantbuy',
        ),
    ]
