# Generated by Django 4.2.11 on 2025-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confsponsor', '0034_rename_instantbuy'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='explicitcontract',
            field=models.BooleanField(default=False, verbose_name='Requested explicit contract'),
        ),
    ]
