# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-12-19 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import postgresqleu.util.validators


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_reverse_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='extra_bcc_list',
            field=models.CharField(blank=True, max_length=500, validators=[postgresqleu.util.validators.ListOfEmailAddressValidator]),
        ),
    ]
