# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-19 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_payment_refector'),
        ('confreg', '0042_paymethods'),
        ('membership', '0004_membership_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicepaymentmethod',
            name='auto',
        ),
    ]
