# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-22 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_generic_bank_transfers'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatValidationCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vatnumber', models.CharField(max_length=100)),
                ('checkedat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
