# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-05-29 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_vatcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingbanktransaction',
            name='canreturn',
            field=models.BooleanField(default=False),
        ),
    ]
