# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-05 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_return_banktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingbanktransaction',
            name='sender',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
