# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-18 19:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_bankfileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatementRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uniqueid', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=300)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other', django.contrib.postgres.fields.jsonb.JSONField(default={}, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('fromfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.BankFileUpload')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bankstatementrow',
            unique_together=set([('uniqueid', 'method')]),
        ),
        migrations.AlterIndexTogether(
            name='bankstatementrow',
            index_together=set([('method', 'date')]),
        ),
        migrations.AddField(
            model_name='bankfileupload',
            name='errors',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
