# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-03-24 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_bankstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicehistory',
            name='txt',
            field=models.CharField(max_length=2000),
        ),
    ]
