# Generated by Django 3.2.14 on 2023-06-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_longer_invoice_history'),
        ('util', '0004_sync_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='extradescription',
            field=models.TextField(blank=True, verbose_name='Extra description'),
        ),
    ]
