# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-05 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0014_return_banktransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnAuthorizationStatus',
            fields=[
                ('checkoutid', models.IntegerField(primary_key=True, serialize=False)),
                ('seencount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StripeCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdat', models.DateTimeField()),
                ('invoiceid', models.IntegerField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sessionid', models.CharField(max_length=200, unique=True)),
                ('paymentintent', models.CharField(max_length=200, unique=True)),
                ('completedat', models.DateTimeField(blank=True, null=True)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StripeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('error', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StripeRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chargeid', models.CharField(max_length=200)),
                ('refundid', models.CharField(max_length=200, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('completedat', models.DateTimeField(blank=True, null=True)),
                ('invoicerefundid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoiceRefund')),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod')),
            ],
        ),
    ]
