# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-07-12 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_return_banktransaction'),
        ('stripepayment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripePayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payoutid', models.CharField(max_length=200, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('sentat', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod')),
            ],
        ),
    ]
