# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-13 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_payment_refector'),
        ('trustlypayment', '0002_nullamount'),
    ]

    operations = [
        migrations.RunSQL("SET CONSTRAINTS ALL IMMEDIATE"),
        migrations.AddField(
            model_name='trustlylog',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AddField(
            model_name='trustlyrawnotification',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AddField(
            model_name='trustlytransaction',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.RunSQL(
            "UPDATE trustlypayment_trustlylog SET paymentmethod_id = (SELECT id FROM invoices_invoicepaymentmethod WHERE classname='postgresqleu.util.payment.trustly.TrustlyPayment') WHERE paymentmethod_id IS NULL",
        ),
        migrations.RunSQL(
            "UPDATE trustlypayment_trustlyrawnotification SET paymentmethod_id = (SELECT id FROM invoices_invoicepaymentmethod WHERE classname='postgresqleu.util.payment.trustly.TrustlyPayment') WHERE paymentmethod_id IS NULL",
        ),
        migrations.RunSQL(
            "UPDATE trustlypayment_trustlytransaction SET paymentmethod_id = (SELECT id FROM invoices_invoicepaymentmethod WHERE classname='postgresqleu.util.payment.trustly.TrustlyPayment') WHERE paymentmethod_id IS NULL",
        ),
        migrations.AlterField(
            model_name='trustlylog',
            name='paymentmethod',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AlterField(
            model_name='trustlyrawnotification',
            name='paymentmethod',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
        migrations.AlterField(
            model_name='trustlytransaction',
            name='paymentmethod',
            field=models.ForeignKey(blank=False, null=False, on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoicePaymentMethod'),
        ),
    ]
