# Generated by Django 4.2.11 on 2025-10-10 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_alter_vatrate_vatpercent'),
        ('trustlypayment', '0004_trustlywithdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='trustlywithdrawal',
            name='matched_refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoicerefund'),
        ),
        migrations.AddField(
            model_name='trustlywithdrawal',
            name='orderid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trustlytransaction',
            name='orderid',
            field=models.BigIntegerField(unique=True),
        ),
    ]
