# Generated by Django 2.2.11 on 2020-08-30 12:24

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membership_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipconfiguration',
            name='sender_name',
            field=models.CharField(default=settings.ORG_NAME, help_text='Name to use as sender on outgoing email', max_length=100),
            preserve_default=False,
        ),
    ]
