# Generated by Django 2.2.11 on 2021-01-22 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_membership_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meetingadmins',
            field=models.ManyToManyField(blank=True, related_name='admin_of_meetings', to='membership.Member', verbose_name='Meeting administrators'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meetingtype',
            field=models.IntegerField(choices=[(0, 'IRC'), (1, 'Web')], default=0, verbose_name='Meeting type'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='state',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Started'), (2, 'Finished'), (3, 'Closed')], default=0),
        ),
        migrations.AddField(
            model_name='membermeetingkey',
            name='allowrejoin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='botname',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bot name'),
        ),
        migrations.CreateModel(
            name='MeetingMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t', models.DateTimeField()),
                ('message', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Meeting')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='membership.Member')),
            ],
            options={
                'ordering': ('meeting', 't'),
            },
        ),
        migrations.AddIndex(
            model_name='meetingmessagelog',
            index=models.Index(fields=['meeting', 't'], name='membership__meeting_84cc48_idx'),
        ),
    ]
