# Generated by Django 2.2.11 on 2021-01-25 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_webmeetings'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendat', models.DateTimeField(verbose_name='Send reminder at', help_text="Reminder will be sent within approximately 15-20 minutes of this timestamp")),
                ('sentat', models.DateTimeField(blank=True, null=True, verbose_name='Reminder sent at')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Meeting')),
            ],
            options={
                'ordering': ('meeting', 'sendat'),
            },
        ),
        migrations.AddIndex(
            model_name='meetingreminder',
            index=models.Index(condition=models.Q(sentat__isnull=True), fields=['sendat'], name='idx_membership_reminder_unsent'),
        ),
    ]
