# Generated by Django 3.2.11 on 2022-02-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_meeting_reminders'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentat', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sentfrom', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=8000)),
                ('sentto', models.ManyToManyField(to='membership.Member')),
            ],
        ),
    ]
