# Generated by Django 3.2.14 on 2023-07-12 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_invoice_extradescription'),
        ('membership', '0008_membermail'),
        ('util', '0004_sync_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='activeinvoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice'),
        ),
    ]
