# Generated by Django 4.2.11 on 2024-08-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_indexupdates'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermail',
            name='sent',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='membermail',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
